# Build the Sage ontologies and their visualization.
#
# This repo owns the ontology pipeline -- merge -> prune -> convert -> strip --
# because the ontology sources live here and the ROBOT / OWL2VOWL jars are fetched
# into tools/ by `make tools`, or on demand by any goal that needs them. A webvowl
# submodule owns the viewer; this Makefile installs the converted ontology into
# it and builds it, serving the result out of webvowl/deploy.
#
#   make tools      fetch the pinned ROBOT and OWL2VOWL jars (neither is committed)
#   make imports    regenerate the checked-in import modules (needs network)
#   make json       just the VOWL JSON (no Node, no submodule needed)
#   make viz        convert the ontology and build the viewer into webvowl/deploy
#   make serve      build viz and serve it as a static site
#   make dev        live-reloading dev server: edit a .ttl, the browser updates
#   make watch      just the ontology watcher (if the dev server already runs)
#   make config     print the resolved paths
#
# Overridable: ROBOT_JAR, OWL2VOWL_JAR, WEBVOWL_DIR, WATCH_INTERVAL.

ROBOT_JAR      ?= tools/robot.jar
OWL2VOWL_JAR   ?= tools/owl2vowl.jar
STRIP_EXTERNAL ?= tools/strip_external_flags.py
IMPORT_SCRIPT  ?= scripts/import.sh

# Both jars are fetched rather than committed, and both are pinned so a rebuild is
# reproducible; bump deliberately.
ROBOT_VERSION ?= 1.9.8
ROBOT_URL     ?= https://github.com/ontodev/robot/releases/download/v$(ROBOT_VERSION)/robot.jar

# OWL2VOWL is fetched from our own mirror because upstream never published a
# runnable artifact for this version: VisualDataWeb's releases 0.3.2-0.3.7 carry no
# assets, and Maven Central stops at 0.3.1 with a 144 KB jar that has no bundled
# dependencies and no Main-Class. The mirrored file is an upstream build (its
# manifest reads Build-Version 0.3.7, Built-By vitalis), so the checksum below is
# what makes that claim checkable -- unlike ROBOT, this is not a first-party
# release, and a silent swap of a 10 MB jar is not something to find out about from
# a broken graph.
OWL2VOWL_VERSION ?= 0.3.7
OWL2VOWL_URL     ?= https://github.com/anngvu/Sage-WebVOWL/releases/download/owl2vowl-$(OWL2VOWL_VERSION)/owl2vowl.jar
OWL2VOWL_SHA256  ?= 2ddc42dc2ff7f66aad48ee8717eef4bd9ddae99aecbbf828c04a8074ea77cfaf

# What gets visualized. ontology/ is split by stability:
#
#   ontology/main/        the ontologies we are actively developing -- built
#   ontology/governance/  the governance model -- unstable, NOT built by default
#   ontology/imports/     third-party vocabularies -- extracted modules, not
#                         whole ontologies; regenerated by `make imports`
#   ontology/shacl/       constraints over the above, currently not visualized:
#                         tests/validate.py checks shapes.
#
# Governance is off until it settles, so the default build is sagebrain plus the
# one import module it reuses terms from. Opt in per invocation:
#
#   make WITH_GOVERNANCE=1 viz
#
# The flag is deliberately not a file list to edit -- flipping it has to be a
# conscious act, and `make config` reports which set is in play.
# sagebrain reuses six Biolink classes by IRI and declares two of its properties
# as subproperties of Biolink ones, so that import module is part of the default
# build -- without it those terms are undeclared and the endpoint-integrity shapes
# fail.
MAIN_SOURCES = ontology/main/sagebrain.ttl \
               ontology/imports/biolink.ttl

GOVERNANCE_SOURCES = ontology/governance/sagegov.ttl \
                     ontology/governance/sagegov_axioms.ttl \
                     ontology/governance/data_ops.ttl \
                     ontology/imports/duo.ttl \
                     ontology/imports/prov.ttl

ONTOLOGY_SOURCES = $(MAIN_SOURCES) $(if $(WITH_GOVERNANCE),$(GOVERNANCE_SOURCES))

# Identity of the built graph is stamped at merge time (see the merge rule).
# Without this the output has an *anonymous* owl:Ontology header -- `robot merge`
# keeps only the first input's, and the governance modules declare none -- and
# the viewer's sidebar reads "No title available" / "No IRI set".
# It gets its own IRI rather than borrowing a module's, even when sagebrain is
# the only input. 
# Hence --remove-annotations on the annotate step: `annotate --annotation` *adds*,
# it does not replace, so without it the output carried two dcterms:title values
# (ours and sagebrain's) and the viewer picked sagebrain's, along with its
# publisher, source and vann: namespace hints.
MERGED_IRI         ?= https://w3id.org/synapse/sagebrain-model
MERGED_VERSION_IRI ?= $(MERGED_IRI)/build
MERGED_TITLE       ?= Sage Ontologies
MERGED_DESCRIPTION ?= Sage Brain ontologies.

# Given as full IRIs because ROBOT's default prefix map does not define dcterms
# for --annotation. dcterms:description rather than rdfs:comment on purpose: VOWL
# files the latter under header.comments, which the viewer's sidebar never reads,
# while header.description is the field it renders.
ANN_TITLE       = http://purl.org/dc/terms/title
ANN_DESCRIPTION = http://purl.org/dc/terms/description

MERGED_TTL = build/ontology_merged.ttl
PRUNED_TTL = build/ontology_pruned.ttl
# Named for the repo, not for one module: the graph is the union of all the
# ontologies above. (It was synbiont.json while sagegov was the only one.)
VOWL_JSON  = build/sage.json

WEBVOWL_DIR ?= webvowl
# webpack packages deploy/data/ from src/app/data/, so the ontology has to be
# installed there *before* `npm run release` or the built app ships without it.
# Must match DEFAULT_JSON_NAME in webvowl/src/app/js/loadingModule.js.
WEBVOWL_DATA         = $(WEBVOWL_DIR)/src/app/data/sage.json
WEBVOWL_NODE_STAMP   = $(WEBVOWL_DIR)/.npm-install
WEBVOWL_DEPLOY       = $(WEBVOWL_DIR)/deploy
WEBVOWL_DEPLOY_INDEX = $(WEBVOWL_DEPLOY)/index.html

# How often the watcher re-checks the ontology sources, in seconds.
WATCH_INTERVAL ?= 1
# Port for `make dev` / `make serve`.
DEV_PORT ?= 3000

# Sanity floor for a converted ontology. Guards against installing a truncated
# graph -- e.g. when two builds race (a foreground `make viz` while `make dev`
# is watching). It has to track the source set: sagebrain plus its biolink import
# module is ~37 classes, so the governance-sized floor would reject every default
# build. Raise both as the ontologies grow.
MIN_CLASSES ?= $(if $(WITH_GOVERNANCE),100,30)

# OWL2VOWL reflects on java.lang internals, which needs an explicit --add-opens
# on Java 16+.
JAVA_OPENS = --add-opens=java.base/java.lang=ALL-UNNAMED

# Obsolete/annotation terms that add noise to the rendered graph.
# NB: '#' must stay escaped in a variable assignment or make reads the rest of
# the line as a comment. (Inside a recipe it would be passed through verbatim.)
PRUNE_TERMS = http://purl.obolibrary.org/obo/IAO_0000102 \
              http://purl.obolibrary.org/obo/IAO_0000314 \
              http://purl.obolibrary.org/obo/IAO_0000632 \
              http://www.geneontology.org/formats/oboInOwl\#ObsoleteClass

# Validate the inputs at parse time so a missing jar or module is named, rather
# than surfacing later as make's "No rule to make target ...".
ifeq ($(filter clean config,$(MAKECMDGOALS)),)
$(if $(wildcard $(STRIP_EXTERNAL)),,$(error Post-processor not found at '$(STRIP_EXTERNAL)'))
$(foreach src,$(ONTOLOGY_SOURCES),$(if $(wildcard $(src)),,$(error Ontology module not found: '$(src)')))
endif

.PHONY: all json viz serve dev watch config tools imports check-submodule clean FORCE

all: viz

json: $(VOWL_JSON)

viz: $(WEBVOWL_DEPLOY_INDEX)

serve: viz
	npx --yes serve $(WEBVOWL_DEPLOY) -l $(DEV_PORT)

# Live-reloading development: edit a .ttl and the open page updates itself.
#
# Two processes, no livereload server needed -- the viewer's dev build polls its
# own ontology JSON and reloads just the ontology when it changes (see
# webvowl/src/app/js/hotReload.js). So this is simply a static server plus the
# converter watcher.
#
# Use `npm run webserver` in the submodule instead if you are editing the
# viewer's own JS/CSS and want those rebuilt too.
dev: viz
	@echo "Serving $(WEBVOWL_DEPLOY) on http://localhost:$(DEV_PORT) and watching the ontology. Ctrl-C stops both."
	@trap 'kill 0' EXIT INT TERM; \
	  npx --yes serve $(WEBVOWL_DEPLOY) -l $(DEV_PORT) & \
	  $(MAKE) --no-print-directory watch & \
	  wait

# Reconverts whenever the sources change. Uses make's own up-to-date check
# rather than tracking hashes, and polls because no filesystem watcher is
# guaranteed to be installed.
#
# The check targets $(VOWL_JSON), not $(WEBVOWL_DATA): the latter has a .PHONY
# order-only prerequisite (check-submodule), and a phony target is always
# considered out of date, so `make -q` on it would report work to do on every
# tick. Staleness of the installed copy is therefore checked directly.
watch:
	@echo "Watching $(words $(ONTOLOGY_SOURCES)) ontology sources for changes (every $(WATCH_INTERVAL)s)"
	@while true; do \
	  if ! $(MAKE) -q --no-print-directory $(VOWL_JSON) >/dev/null 2>&1 \
	     || [ ! -f "$(WEBVOWL_DATA)" ] \
	     || [ "$(VOWL_JSON)" -nt "$(WEBVOWL_DATA)" ]; then \
	    echo "--- ontology changed, reconverting"; \
	    $(MAKE) --no-print-directory $(WEBVOWL_DATA) \
	      || echo "--- conversion failed; waiting for the next change"; \
	  fi; \
	  sleep $(WATCH_INTERVAL); \
	done

config:
	@echo "ROBOT_JAR      = $(ROBOT_JAR)$(if $(wildcard $(ROBOT_JAR)), [ok], [not fetched yet -- run 'make tools'])"
	@echo "OWL2VOWL_JAR   = $(OWL2VOWL_JAR)$(if $(wildcard $(OWL2VOWL_JAR)), [ok], [not fetched yet -- run 'make tools'])"
	@echo "STRIP_EXTERNAL = $(STRIP_EXTERNAL)$(if $(wildcard $(STRIP_EXTERNAL)), [ok], [missing])"
	@echo "WEBVOWL_DIR    = $(WEBVOWL_DIR)$(if $(wildcard $(WEBVOWL_DIR)/package.json), [ok], [submodule not initialised])"
	@echo "VOWL_JSON      = $(VOWL_JSON)"
	@echo "WEBVOWL_DATA   = $(WEBVOWL_DATA)"
	@echo "WEBVOWL_DEPLOY = $(WEBVOWL_DEPLOY)"
	@echo "VIEWER_BUILD   = $(VIEWER_BUILD)$(if $(BUILT_MODE), [deploy/ currently holds a '$(BUILT_MODE)' build],)"
	@echo "MIN_CLASSES    = $(MIN_CLASSES)"
	@echo "governance     = $(if $(WITH_GOVERNANCE),INCLUDED (WITH_GOVERNANCE=$(WITH_GOVERNANCE)),excluded -- pass WITH_GOVERNANCE=1 to build it)"
	@echo "sources        = $(words $(ONTOLOGY_SOURCES)) file(s):"
	@$(foreach src,$(ONTOLOGY_SOURCES),echo "                 $(src)$(if $(wildcard $(src)),, [MISSING])";)

# ROBOT is not committed; this fetches the pinned release.
$(ROBOT_JAR):
	@echo "Fetching ROBOT $(ROBOT_VERSION) (not committed -- 78 MB)"
	mkdir -p $(dir $@)
	curl -L --fail -o $@.tmp "$(ROBOT_URL)"
	mv $@.tmp $@

# Written via a temp file and checksummed before it is moved into place, so an
# interrupted or corrupted download cannot leave a jar that looks fetched.
$(OWL2VOWL_JAR):
	@echo "Fetching OWL2VOWL $(OWL2VOWL_VERSION) (not committed -- 10 MB)"
	mkdir -p $(dir $@)
	curl -L --fail -o $@.tmp "$(OWL2VOWL_URL)"
	@echo "$(OWL2VOWL_SHA256)  $@.tmp" | sha256sum --check --status \
	  || { echo "ERROR: checksum mismatch on $(OWL2VOWL_URL)"; \
	       echo "       expected $(OWL2VOWL_SHA256)"; \
	       echo "       got      $$(sha256sum $@.tmp | cut -d' ' -f1)"; \
	       rm -f $@.tmp; exit 1; }
	mv $@.tmp $@

tools: $(ROBOT_JAR) $(OWL2VOWL_JAR)

check-submodule:
	@test -f "$(WEBVOWL_DIR)/package.json" || { \
	  echo "ERROR: the webvowl submodule is not initialised at '$(WEBVOWL_DIR)'."; \
	  echo "       Run: git submodule update --init --recursive"; \
	  echo "       (or point elsewhere with WEBVOWL_DIR=/path/to/webvowl)"; \
	  exit 1; }

# The import modules under ontology/imports/ are committed, and nothing in the
# pipeline depends on this target: regenerating them goes to the network, and a
# build that can silently pull a different upstream version is not reproducible.
# So this is opt-in, and the diff it produces is meant to be read before it is
# committed. The module list, the pinned versions and the extraction method live
# in the script.
imports:
	$(IMPORT_SCRIPT)


# --- ontology pipeline ------------------------------------------------------

# Depends on this Makefile as well: ONTOLOGY_SOURCES and PRUNE_TERMS live here,
# and adding a source whose mtime is older than the last build would otherwise
# leave the merge looking up to date. Rebuilding the chain on a Makefile edit
# costs ~3s and removes that whole class of stale output.
# `annotate` is chained onto `merge` rather than run as its own step: ROBOT pipes
# one command into the next in a single JVM, so the header costs nothing extra.
$(MERGED_TTL): $(ONTOLOGY_SOURCES) Makefile | $(ROBOT_JAR)
	mkdir -p $(dir $@)
	java -jar $(ROBOT_JAR) merge \
		$(foreach src,$(ONTOLOGY_SOURCES),-i $(src)) \
		annotate --remove-annotations \
			--ontology-iri "$(MERGED_IRI)" \
			--version-iri "$(MERGED_VERSION_IRI)" \
			--annotation $(ANN_TITLE) "$(MERGED_TITLE)" \
			--annotation $(ANN_DESCRIPTION) "$(MERGED_DESCRIPTION)" \
		-o $@

$(PRUNED_TTL): $(MERGED_TTL) | $(ROBOT_JAR)
	mkdir -p $(dir $@)
	java -jar $(ROBOT_JAR) remove \
		--input $< \
		$(foreach term,$(PRUNE_TERMS),--term $(term)) \
		--select "self descendants" \
		--output $@

# Written via a temp file so the target only ever exists in its finished,
# post-strip state. Stripping $@ in place meant an interrupted build left a
# raw conversion behind, and make -- seeing a target newer than its
# prerequisites -- would never redo the strip.
$(VOWL_JSON): $(PRUNED_TTL) $(STRIP_EXTERNAL) | $(OWL2VOWL_JAR)
	mkdir -p $(dir $@)
	tmp=$@.$$$$.tmp; \
	  java $(JAVA_OPENS) -jar $(OWL2VOWL_JAR) -file $(PRUNED_TTL) -output $$tmp && \
	  python3 $(STRIP_EXTERNAL) $$tmp && \
	  python3 -c "import json,sys; d=json.load(open('$$tmp')); n=len(d.get('class',[])); \
	    sys.exit(0) if n >= $(MIN_CLASSES) else (print('ERROR: conversion produced only %d classes (expected >= $(MIN_CLASSES)); refusing to install' % n) or sys.exit(1))" && \
	  mv $$tmp $@ || { rm -f $$tmp; exit 1; }


# --- viewer ----------------------------------------------------------------

# Installs into the viewer's source tree, and -- if a build already exists --
# straight into deploy/ as well. That second copy is what makes the watch loop
# self-contained: the running page polls deploy/data and reloads itself, so no
# grunt watch or livereload server has to be involved.
$(WEBVOWL_DATA): $(VOWL_JSON) | check-submodule
	mkdir -p $(dir $@)
	cp $< $@
	@if [ -d "$(WEBVOWL_DEPLOY)/data" ]; then \
	  cp $< $(WEBVOWL_DEPLOY)/data/$(notdir $@); \
	  echo "    also refreshed $(WEBVOWL_DEPLOY)/data/$(notdir $@)"; \
	fi

$(WEBVOWL_NODE_STAMP): $(WEBVOWL_DIR)/package.json | check-submodule
	cd $(WEBVOWL_DIR) && npm install
	touch $@

# `npm run release` strips the viewer's dev-only hot-reload hook; `npm run
# package` keeps it. `make dev` wants the dev bundle, every other goal the
# release one. Decided here at parse time rather than as a `dev:`-specific
# variable, because the stamp comparison below has to see it -- and because
# target-specific variables are not inherited by the recursive $(MAKE) calls in
# `dev`. Override with `make VIEWER_BUILD=package viz`.
ifneq ($(filter dev,$(MAKECMDGOALS)),)
VIEWER_BUILD ?= package
else
VIEWER_BUILD ?= release
endif

# Both builds write the same deploy/index.html, so make cannot tell them apart by
# mtime: after a `make dev`, a plain `make viz` found the target up to date and
# left the *dev* build in place -- hot-reload polling and all -- while reporting
# success.
#
# So ask the artifact which build made it, rather than recording it: only the dev
# build keeps the hot-reload hook. Reading the answer off deploy/ instead of a
# stamp means it stays right even when the viewer was built directly with
# `npm run package` / `npm run release`, which is normal while working on the
# viewer itself. If that hook is ever renamed in webvowl/src/index.html, this
# marker has to change with it.
DEV_BUILD_MARKER = WEBVOWL_HOT_RELOAD
BUILT_MODE := $(shell test -f $(WEBVOWL_DEPLOY_INDEX) && \
                { grep -q '$(DEV_BUILD_MARKER)' $(WEBVOWL_DEPLOY_INDEX) \
                  && echo package || echo release; })

# Empty means nothing is built yet, and the ordinary prerequisites handle that.
# A mismatch pulls in FORCE, which never exists and so is never up to date.
ifneq ($(BUILT_MODE),)
ifneq ($(BUILT_MODE),$(VIEWER_BUILD))
VIEWER_BUILD_CHANGED = FORCE
endif
endif

FORCE:

# Depends on the installed ontology, so the build always bundles it.
$(WEBVOWL_DEPLOY_INDEX): $(WEBVOWL_DATA) $(WEBVOWL_NODE_STAMP) $(VIEWER_BUILD_CHANGED)
	cd $(WEBVOWL_DIR) && npm run $(VIEWER_BUILD)

# Deliberately keeps tools/robot.jar -- re-downloading 78 MB is not "clean".
clean:
	rm -f $(MERGED_TTL) $(PRUNED_TTL) $(VOWL_JSON) $(VOWL_JSON).*.tmp $(WEBVOWL_DATA)
